common-platform-requests
bcgov/platform-developer-docs pull request #237
Opened 2024-04-15 16:49 UTC by Pilargit12

From support page on digital.gov.bc.ca creating common platform requests on tech docs.  Team to advise if there are other common platform requests that need to be added to this page

2024-04-16 15:56 UTC, mtspn requested changes
Looks good, I just think these links could use a slight tweak.

2024-04-16 15:56 UTC, mtspn commented on src/docs/openshift-projects-and-access/common-platform-requests.md
> +Only the Platform Services team can create new private repositories in the bcgov-c GitHub organization.
```suggestion
Requests to create new private repositories in the bcgov-c github organization must be approved by the Platform Services Team.
```

2024-04-16 15:56 UTC, mtspn commented on src/docs/openshift-projects-and-access/common-platform-requests.md
> +[Submit a request to create a private repository.](https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2FBCDevOps%2Fdevops-requests%2Fissues%2Fnew%3Fassignees%3Dcaggles%252C%2BShellyXueHan%25
```suggestion
[Request for private BCGOV GitHub Repository](https://github.com/BCDevOps/devops-requests/issues/new/choose)
```

2024-04-16 15:56 UTC, mtspn commented on src/docs/openshift-projects-and-access/common-platform-requests.md
> +Only the Platform Services team can create new private repositories in the bcgov-c GitHub organization.
Suggested change to remove the possible implication that only platform services team can create these requests.

2024-04-16 15:56 UTC, mtspn commented on src/docs/openshift-projects-and-access/common-platform-requests.md
> +[Submit a request to create a private repository.](https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2FBCDevOps%2Fdevops-requests%2Fissues%2Fnew%3Fassignees%3Dcaggles%252C%2BShellyXueHan%25
Linking to general issue creation page, rather than the markdown file for a specific issue.

2024-04-16 15:56 UTC, mtspn commented on src/docs/openshift-projects-and-access/common-platform-requests.md
> +[Submit a request to remove GitHub or OpenShift membership.](https://github.com/BCDevOps/devops-requests/issues/new?assignees=caggles%2C+ShellyXueHan%2C+mitovskaol%2C+patricksimonian&labels=github-me
```suggestion
[Request to remove OpenShift Access and or BCGOV GitHub Organization Membership](https://github.com/BCDevOps/devops-requests/issues/new/choose)
```

2024-04-16 15:56 UTC, mtspn commented on src/docs/openshift-projects-and-access/common-platform-requests.md
> +[Submit a request to remove GitHub or OpenShift membership.](https://github.com/BCDevOps/devops-requests/issues/new?assignees=caggles%2C+ShellyXueHan%2C+mitovskaol%2C+patricksimonian&labels=github-me
As above, linking to the general issue creation page rather than the markdown file for the issue. Matching the link name to the issue name.

2024-04-16 16:01 UTC, Pilargit12 reviewed
Thank you Matt!

2024-04-16 16:03 UTC, mtspn approved these changes

2024-04-16 19:21 UTC, mtspn requested changes
Some further changes may be needed after discussion with Jen

2024-04-17 14:38 UTC, mtspn approved these changes

2024-04-17 14:38 UTC, mtspn commented on src/docs/openshift-projects-and-access/common-platform-requests.md
> +Requests to create new private repositories in the bcgov-c github organization must be approved by the Platform Services Team.
```suggestion
Requests to create new private repositories in the bcgov-c github organization must be approved by the Developer Experience Team.
```

2024-04-17 14:38 UTC, mtspn commented on src/docs/openshift-projects-and-access/common-platform-requests.md
> +There are a limited number of spots available in the bcgov-c organization. If there are no spots remaining, you’ll receive an error message when you try to add a new user. If this occurs, send a requ
```suggestion
There are a limited number of spots available in the bcgov-c organization. If there are no spots remaining, you’ll receive an error message when you try to add a new user. If this occurs, send a request to [developer.experience@gov.bc.ca](mailto:developer.experience@gov.bc.ca) for an additional spot to the Developer Experience Team. Once they confirm your request has been completed, you can add the new user to your repository.
```

2024-04-17 14:39 UTC, mtspn commented on src/docs/openshift-projects-and-access/common-platform-requests.md
> +The Platform Services team removes bcgov-c organization access for users that have not been active for 6 months. Once access has been removed, users must be re-invited to the organization and re-adde
```suggestion
The Developer Experience team removes bcgov-c organization access for users that have not been active for 6 months. Once access has been removed, users must be re-invited to the organization and re-added to a repository to gain access.
```

2024-04-17 17:02 UTC, w8896699 approved these changes
LGTM

2024-04-17 18:40 UTC, merged