Add Defunct PIDs page
bcgov/platform-developer-docs pull request #259
Opened 2024-06-25 21:38 UTC by StevenBarre

2024-06-25 21:40 UTC, tbaker1313 approved these changes

2024-06-25 21:56 UTC, IanKWatts approved these changes

2024-06-25 22:47 UTC, wmhutchison approved these changes
👍

2024-06-28 18:05 UTC, Pilargit12 requested changes
Minor changes and we are missing an quick introduction to the subject as well

2024-06-28 18:05 UTC, Pilargit12 commented on src/docs/platform-automation/defunct-pids.md
> +The first process to start in a container is treated as PID 1 and all other processes are treated as children of that process. If that process is not expecting to be parent to other processes, then w
```suggestion
The first process in a container is PID 1, and all others are its children. If PID 1 doesn't expect to parent other processes when those child processes exit in unexpected ways, they can become zombie or defunct, needing cleanup.
```

2024-06-28 18:05 UTC, Pilargit12 commented on src/docs/platform-automation/defunct-pids.md
> +The proper fix is to ensure that the `ENTRYPOINT` of your container is a process that can handle the cleanup of zombie child processes, often called an init program. Some examples include [Tini](http
```suggestion
The proper solution is to set your container's `ENTRYPOINT` to a process that handles zombie child processes cleanup, called an init program. Examples include [Tini](https://github.com/krallin/tini), [dumb-init](https://github.com/Yelp/dumb-init), and [s6-overlay](https://github.com/just-containers/s6-overlay). Using one of these init processes as PID 1 ensures that unhandled defunct PIDs are cleaned up, preventing issues for the node's kernel.
```

2024-06-28 18:05 UTC, Pilargit12 commented on src/docs/platform-automation/defunct-pids.md
> +Sometimes minor changes to the probes can also be done to prevent them from creating zombies as well.
```suggestion
Sometimes, minor changes to the probes can prevent them from creating zombie processes.
```

2024-06-28 18:05 UTC, Pilargit12 commented on src/docs/platform-automation/defunct-pids.md
> +## Additional Reading
```suggestion
## Additional resources
```

2024-06-28 18:05 UTC, Pilargit12 commented on src/docs/platform-automation/defunct-pids.md
> +- [Container Init Process](https://devopsdirective.com/posts/2023/06/container-init-process/)
```suggestion
- [Container Init process](https://devopsdirective.com/posts/2023/06/container-init-process/)
```

2024-06-28 18:05 UTC, Pilargit12 commented on src/docs/platform-automation/defunct-pids.md
> +- [Kubernetes Feature Request to add init process to all containers](https://github.com/kubernetes/kubernetes/issues/84210)
```suggestion
- [Kubernetes feature request to add init process to all containers](https://github.com/kubernetes/kubernetes/issues/84210)
```

2024-06-28 18:05 UTC, Pilargit12 commented on mkdocs.yml
> +  - Defunct PIDs: docs/platform-automation/defunct-pids.md
```suggestion
  - Defunct Process IDs (PIDs): docs/platform-automation/defunct-pids.md
```

2024-06-28 18:05 UTC, Pilargit12 commented on src/docs/platform-automation/defunct-pids.md
> +title: Defunct PIDs
```suggestion
title: Defunct Process IDs (PIDs)
```

2024-06-28 19:56 UTC, Pilargit12 approved these changes

2024-07-04 19:34 UTC, Pilargit12 commented
Hi @StevenBarre if you are happy, please feel free to merge to main, thank you!

2024-07-04 21:21 UTC, StevenBarre commented
Thanks, still working on the actual code part. Will merge once its ready to launch.

2024-07-12 16:06 UTC, merged