Chatbot user manual
bcgov/platform-developer-docs pull request #264
Opened 2024-07-19 22:56 UTC by ShellyXueHan

### Update:
This is the user manual for the community chatbot. keeping it fun since we don't anticipate it to be a "fully supported" service.

Also I'm not sure where best to add this doc to, so starting from here!

2024-08-01 20:29 UTC, StevenBarre commented on src/docs/training-and-learning/rocky-guide.md
> +So, let’s get started! Head over to the [rocky-chat channel](https://chat.developer.gov.bc.ca/group/rocky-chat) and call me with `!Rocky` followed by your questions. Ask away!
```suggestion
So, let’s get started! Head over to the [rocky-chat channel](https://chat.developer.gov.bc.ca/channel/rocky-chat) and call me with `!Rocky` followed by your questions. Ask away! 
```
It's a channel not a group.

2024-12-02 17:44 UTC, Pilargit12 requested changes
Hi @ShellyXueHan, went through the document, looks great! Just a couple of things for clarity and plain language. 

I was wondering if you could add perhaps something about support if something is broken? Who are users supposed to contact?

2024-12-02 17:44 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +- [BC Government Private Cloud Private Cloud website](http://digital.gov.bc.ca/cloud/services/private)
```suggestion
- [B.C. Government Private Cloud Private Cloud website](http://digital.gov.bc.ca/cloud/services/private)
```

2024-12-02 17:44 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +- [Technical Documentation website](https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/)
```suggestion
- [Private cloud technical documentation website](https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/)
```

2024-12-02 17:44 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +- **Got Questions about OpenShift?** 🤔 I’ve got answers! Just ask me anything related to OpenShift platform usage, and I’ll fetch the info from our knowledge base faster than you can say “Kubernetes!
```suggestion
- **Have questions about OpenShift?** 🤔 I’ve got answers! Ask me anything about using the OpenShift platform, and I’ll pull info from our knowledge base faster than you can say “Kubernetes!”
```

2024-12-02 17:44 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +- **Need Info from the websites above?** 🌐 I’m a pro at digging up details from these sites. Whether it’s a questions for the how-tos, troubleshooting, or best practices, as long as it's there somewh
```suggestion
- **Need info from the sites above?** 🌐 I’m great at finding details! Whether it’s how-tos, troubleshooting tips, or best practices, if it’s on those sites, I’ll track it down for you.
```

2024-12-02 17:44 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +> Remember, I’m all about OpenShift and those specific websites. If you ask me something outside my wheelhouse, I’ll redirect you to our community powered channel at #devops-how-to for some real huma
```suggestion
> Remember, I’m here to help with OpenShift and the websites I know. If your question is outside my expertise, I’ll point you to our community-powered channel, [#devops-how-to](https://chat.developer.gov.bc.ca/channel/devops-how-to), where real humans can assist you better.
```

2024-12-02 17:44 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +- **Got Feedback?** 💬 Yes please! I need feedback to continue to grow. Simply give it a thumb up or down to my answer and I'll take it from there! If you have any feedback or suggestions more than th
```suggestion
- **Got feedback?** 💬 I’d love it! Your feedback helps me improve. Give my answer a thumbs up or down, and I’ll take it from there. If you have more detailed feedback or suggestions, please ping my human caregiver at `@shelly.han`. We’re eager to hear from you! 
```

2024-12-02 17:44 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +So, let’s get started! Head over to the [rocky-chat channel](https://chat.developer.gov.bc.ca/channel/rocky-chat) and call me with `!rocky`, followed by your questions. Ask away!
```suggestion
Let’s get started! Head over to the [rocky-chat channel](https://chat.developer.gov.bc.ca/channel/rocky-chat) and call me with `!rocky`, followed by your questions. Ask away!
```

2024-12-02 17:44 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +Note that while interacting with me, please do not include any sensitive personal information in your conversation. This would include any reference to religious beliefs, government service history,
```suggestion
**Important**: Please don’t include sensitive personal information when chatting with me. This includes details about religious beliefs, government service history, sexuality, gender, health, private ID numbers, or similar data.
```

2024-12-02 17:44 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +### Wonder how I work?
```suggestion
### Curious about how I work?
```

2024-12-02 17:44 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +There are several parts of me that work together:
```suggestion
Here’s a quick look behind the scenes:
```

2024-12-02 17:44 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +- My DNA sequence 🧬 is recorded in Rocky repo: https://github.com/bcgov/rockychat
```suggestion
- My DNA 🧬 is stored in the [Rocky repo](https://github.com/bcgov/rockychat)
```

2024-12-02 17:44 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +- I live in the Silver cluster, as you might have guessed, I have a sibling called Rocky Test. I'm jealous of him, he gets to try out everything new before me! But anyway, only I get to talk to you 😃
```suggestion
- I live in the Silver cluster alongside my sibling, Rocky Test. (He gets to test new features first—I’m totally not jealous! 😅) But I’m the one you get to talk to!
```

2024-12-02 17:44 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +- My brain 🧠 is always evolving, currently you are talking to GPT4 from [Azure OpenAI](https://azure.microsoft.com/en-us/products/ai-services/openai-service). I'm always learning and improving!
```suggestion
- My brain 🧠 is powered by GPT-4 through [Azure OpenAI](https://azure.microsoft.com/en-us/products/ai-services/openai-service) and I’m always learning and improving!
```

2024-12-02 17:44 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +# Platform Services GenAI Chatbot - Rocky
```suggestion
# Platform Services GenAI chatbot: Rocky
```

2024-12-02 18:20 UTC, Pilargit12 approved these changes

2024-12-02 21:17 UTC, Pilargit12 reviewed
Just minor updates and then should be good to go!

2024-12-02 21:17 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +🎉 Hi! I’m Rocky from the Platform Services team, your friendly AI assistant in Rocket.Chat! 🤖✨ I’m here to help with the OpenShift platform and its related shared services. I’ve been trained using kn
```suggestion
Hi! I’m Rocky from the Platform Services team, your friendly AI assistant in Rocket.Chat! 🤖✨ I’m here to help with the OpenShift platform and its related shared services. I’ve been trained using knowledge from these sources:
```

2024-12-02 21:17 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +## If something went wrong:
```suggestion
## Troubleshooting Rocky chatbot
```

2024-12-02 21:17 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +## Here’s how I can help you out:
```suggestion
## How I help you
```

2024-12-02 21:17 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +- If you asked a question and didn't hear back from me, please first check if you tagged me with `!rocky` (I'm not case sensitive but don't miss the exclamation mark). If still no response, please ta
```suggestion
- If you asked a question and didn't hear back from me, please first check if you tagged me with `!rocky` (I'm not case sensitive but don't miss the exclamation mark). If there's no response still, please tag `@shelly.han` for support!
```

2024-12-02 21:17 UTC, Pilargit12 commented on src/docs/training-and-learning/rocky-guide.md
> +- If there are specific issues, concerns, and feature requests, please create them as a Github Issue in the [Rocky repo](https://github.com/bcgov/rockychat).
```suggestion
- If there are specific issues, concerns and/or feature requests, please create them as a Github Issue in the [Rocky repo](https://github.com/bcgov/rockychat).
```

2024-12-02 23:20 UTC, ShellyXueHan commented on mkdocs.yml
> +  - Platform Services GenAI chatbot: Rocky: docs/training-and-learning/rocky-guide.md
```suggestion
  - Platform Services GenAI chatbot Rocky: docs/training-and-learning/rocky-guide.md
```

2024-12-03 16:47 UTC, merged