Updates for AlertmanagerConfig and PrometheusRule
bcgov/platform-developer-docs pull request #285
Opened 2024-10-22 16:41 UTC by StevenBarre

- How to create long term silences
- How to customize alert receivers
- Update the list of alerts to match https://github.com/bcgov-c/devops-fulfillment-pipeline/pull/185
- Update the frequency to match https://github.com/bcgov-c/devops-fulfillment-pipeline/pull/185

2024-10-22 17:10 UTC, tbaker1313 commented on src/docs/app-monitoring/user-defined-monitoring.md
> +If you want to use an email receiver, keep it the same an only update the `name` and `to` fields, as well as the `Product Name Here` in the `html`. The rest ensures that the email is sent correctly a
```suggestion
If you want to use an email receiver, keep it the same and only update the `name` and `to` fields, as well as the `Product Name Here` in the `html`. The rest ensures that the email is sent correctly and with nice formatting.
```

2024-10-22 18:12 UTC, wmhutchison approved these changes
👍

2024-10-22 18:14 UTC, tbaker1313 approved these changes

2024-10-25 20:57 UTC, caggles requested changes
looks good, just two small updates suggested, and then I think we could merge this!

2024-10-25 20:57 UTC, caggles commented on src/docs/platform-automation/alertmanager.md
> +## Silencing Alerts
```suggestion
## Silencing alerts
```

Pilar says best practice is to capitalize only the first word in a title (or proper nouns, etc)

2024-10-25 20:57 UTC, caggles commented on src/docs/platform-automation/alertmanager.md
> +- [Silencing Alerts](#silencing-alerts)
```suggestion
- [Silencing alerts](#silencing-alerts)
```

2024-10-28 22:45 UTC, caggles approved these changes

2024-10-28 22:48 UTC, merged