documentation check point at Saturation
bcgov/platform-developer-docs pull request #86
Opened 2022-07-20 22:16 UTC by w8896699

2022-07-22 21:27 UTC, ShellyXueHan requested changes
There are many grammar issues with this doc, please do a proofread before PR next time. Also I can see you are taking contents from other resources, in this case it's better to just put a reference to the original document instead of creating duplications. In terms of the promQL samples, I think they are too basic. For example, the resource usage ones are only reflecting namespace overall status, where a useful metrics would be grouped by workloads or service components. Also it would be better to provide a full query for the network request related monitors instead of a simple metric. All in all i think this would need some rework. Let's chat about it next week before you put more efforts in.

2022-07-22 21:27 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +title: Sysdig Monitoring Guildline for shared services and apps
```suggestion
title: Sysdig Monitoring Guideline for Platform Shared Services
```

2022-07-22 21:27 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +description: Default monitoring standards that will be applied to all our services and apps.
```suggestion
description: Service Golden Signal - monitoring standards and best practise that will be applied to Platform Shared Services.
```

2022-07-22 21:27 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +The four golden signals of SRE are latency, traffic, errors, and saturation. SRE’s golden signals define what it means for the system to be “healthy.”  And our monitoring standard will be build based
```suggestion
The four golden signals of Site Reliability Engineering (SRE) are latency, traffic, errors, and saturation. SRE’s golden signals define what it means for the system to be “healthy”. The following monitoring standard will be built based on those four aspects.
```

2022-07-22 21:27 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +The Prometheus Query Language (PromQL) is the defacto standard for querying Prometheus metric data. PromQL is designed to allow the user to select and aggregate time-series data. And building dashboa
```suggestion
The Prometheus Query Language (PromQL) is the defacto standard for querying Prometheus metric data. PromQL is designed to allow the user to select and aggregate time-series data. And building dashboard in Sysdig is heavily relying on PromQL. The PromQL language is documented at [Prometheus Query Basics](https://prometheus.io/docs/prometheus/latest/querying/basics/).
```

2022-07-22 21:27 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +# Resources monitoring with Sysdig(Saturation)
```suggestion
## Resources monitoring with Sysdig (Saturation)
```

2023-08-28 18:45 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +The registry is an application where teams can submit requests for provisioning namespaces in OpenShift 4 (OCP4) clusters. The registry allows teams to:
let's call it `BC Platform Services Product Registry` for more accurate naming ;)

2023-08-28 18:45 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +- Receive management from the platform services team.
does registry actually do number 2 and 3 (with keycloak realms)??? also what does `Receive management` mean

2023-08-28 18:45 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +More details about the Registry app and its workings can be found [here](https://github.com/bcgov/platform-services-registry/blob/master/docs/Whole-project-workflow.md).
the link is invalid

2023-08-28 18:45 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +* DB should have a backup every 30 mins
can you explain why a backup every 30 mins, for example which SLA does this match to?

2023-08-28 18:45 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +The registry is an application where teams can submit requests for provisioning namespaces in OpenShift 4 (OCP4) clusters. The registry allows teams to:
maybe helpful to describe the project structure: API, web frontend, DB, automation provisioner, etc...

2023-08-28 18:45 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +The definition of s SLO is a service level objective: a target value or range of values for a service level that is measured by an SLI. Google has a really [good doc](https://sre.google/workbook/impl
```suggestion
The definition of SLO is a service level objective: a target value or range of values for a service level that is measured by an SLI. Google has a really [good doc](https://sre.google/workbook/implementing-slos/#:~:text=For%20example%2C%20if%20you%20have,50%25%20of%20the%20error%20budget.) for how to gets the start.
```

2023-08-28 18:45 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +* Provisioner jobs can be completed within 40 mins
app teams won't understand that provisioner jobs correspond to "Update product requests" in SLA if there is no explaination how things work. might be better to name it as `automation jobs for OCP Project Set change requests`

2023-08-28 18:45 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +The definition of s SLO is a service level objective: a target value or range of values for a service level that is measured by an SLI. Google has a really [good doc](https://sre.google/workbook/impl
based on the google link, it's important to know how to calculate error budget if ppl were to use the error budget–based approach for reliability, can you provide more details on that end?

2023-08-28 18:45 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +* Number of successful HTTP requests / total HTTP requests (success rate) should be greater than 99.99%
how does this SLIs related to the SLO and SLA defined earlier? for example, why 99.99%? Does is correspond to "Web, API, and DB should be up 99.5% of the time"?

2023-08-28 18:45 UTC, ShellyXueHan commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +### Team Scope
why is this section named as team scope?

2023-09-25 20:53 UTC, w8896699 commented
@Pilargit12

2023-09-26 14:41 UTC, Pilargit12 commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +title: SRE Guideline for Platform Shared Services
In the PR it the file .md still reads Sysdig-Monitoring-**Guidline**-for-shared-services-and-apps please make sure to update it correctly, I believe @ShellyXueHan made a suggestion 

Slug of the website should also be all lower case: sysdig-monitor-setup

2023-09-26 14:55 UTC, Pilargit12 commented on src/docs/app-monitoring/Sysdig-Monitoring-Guidline-for-shared-services-and-apps.md
> +
Last updated: **Month, day, year**

2023-09-26 21:58 UTC, Pilargit12 approved these changes
Looks good to me, I wonder if other team members will have time to review this new doc.

2024-01-29 18:43 UTC, w8896699 commented
@ShellyXueHan may I merge this? been hanging for a long while

2024-01-30 17:59 UTC, ShellyXueHan commented on src/docs/app-monitoring/sysdig-monitoring-guideline-for-shared-services-and-apps.md
> +The meaning of an SLO is a service level objective: it's a specified target value or a range of values for a service level that gets measured through an SLI. Google offers a [valuable workbook](https
```suggestion
SLO is a specified target value or a range of values for a service level that gets measured through an SLI. Google offers a [valuable workbook](https://sre.google/workbook/implementing-slos/#:~:text=For%20example%2C%20if%20you%20have,50%25%20of%20the%20error%20budget.) written by Steven Thurgood, David Ferguson with Alex Hidalgo and Betsy Beyer to assist you in implementing SLOs. Towards the end of this document, we will also delve into calculating the Error Budget in more detail.
```
in addition, can we avoid using acronyms before explaining what they are, i.e. `...gets measured through an SLI` while ppl might not know what SLI stand for. Or consider adding a link to them to point to a later section for reference?

2024-01-30 17:59 UTC, ShellyXueHan commented on src/docs/app-monitoring/sysdig-monitoring-guideline-for-shared-services-and-apps.md
> +Once again, I'll use the Registry as an example, and we'll consider monthly periods:
can you explain what a monthly period is? it should be a continuous 30 day window instead of calendar months.

2024-01-30 19:17 UTC, ShellyXueHan commented on src/docs/app-monitoring/sysdig-monitoring-guideline-for-shared-services-and-apps.md
> +SLI golden signals consist of request latency, availability, error rate, and system throughput. These metrics establish the criteria for determining the system's "health." It's essential to grasp the
```suggestion
SLI golden signals consist of request latency, availability, error rate, and system throughput. These metrics establish the criteria for determining the system's "health". It's essential to grasp the connection and difference between SLIs, SLOs, and SLAs.
```

2024-01-30 19:17 UTC, ShellyXueHan commented on src/docs/app-monitoring/sysdig-monitoring-guideline-for-shared-services-and-apps.md
> +SLI golden signals consist of request latency, availability, error rate, and system throughput. These metrics establish the criteria for determining the system's "health." It's essential to grasp the
so what's the difference and connection between SLI, SLO and SLA?

2024-01-30 19:17 UTC, ShellyXueHan commented on src/docs/app-monitoring/sysdig-monitoring-guideline-for-shared-services-and-apps.md
> +**Performance Monitoring Tools:**  You can use tools like Prometheus, Grafana, or New Relic to continuously watch and display system performance metrics, including response times
could you add the relative doc links so ppl know how to get started?

2024-01-30 19:17 UTC, ShellyXueHan commented on src/docs/app-monitoring/sysdig-monitoring-guideline-for-shared-services-and-apps.md
> +To achieve 99.5% uptime, we have a daily allowance of just 7 minutes and 12 seconds for downtime. This is where RunBooks prove invaluable. In SRE, the objective is to automate as many processes as fe
could you include a brief explanation on runbook, like an automated script that ....

2024-01-30 19:17 UTC, ShellyXueHan commented on src/docs/app-monitoring/sysdig-monitoring-guideline-for-shared-services-and-apps.md
> +For more insights on automation runbooks, refer to this [source in Xenonstack](https://www.xenonstack.com/insights/automation-runbook-for-sre). We are also introducing [runwhen](https://www.runwhen.c
we don't use runwhen ourselves, but you could say here's a cool tool for that ;)

2024-01-30 19:17 UTC, ShellyXueHan commented on src/docs/app-monitoring/sysdig-monitoring-guideline-for-shared-services-and-apps.md
> +This means that the service can be "unreliable" or "down" for 5% of the time without violating the SLO.
also need to set the length of the calculation time window

2024-01-30 19:17 UTC, ShellyXueHan commented on src/docs/app-monitoring/sysdig-monitoring-guideline-for-shared-services-and-apps.md
> +1. **Monitoring**: It's not just about observing; it's our initial defense against issues. The sooner we notice something, the faster we can address it.
and the less impact it cause!

2024-08-02 16:01 UTC, Pilargit12 commented
@w8896699  what happened to this branch ? Do we need to keep it open?

2024-09-20 15:59 UTC, Pilargit12 commented
I am doing a cleaning of tech doc branches that were never reviewed again, nor merged (maybe this is too late). @w8896699 or @ShellyXueHan   can this be closed?

2024-09-20 15:59 UTC, closed without merging